[package]
name = "poac_api_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2", features = ["postgres", "r2d2"] }
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
