runtime: go111

handlers:
- url: /.*
  script: auto
  secure: always
- url: /flush-memcache
  script: auto
  login: admin
  auth_fail_action: unauthorized
  secure: always
- url: /firestore-export
  script: auto
  login: admin
  auth_fail_action: unauthorized
  secure: always
