[package]
name = "poac-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.9"
diesel = { version = "2", features = ["postgres", "r2d2", "uuid"] }
dotenvy = "0.15"
log = "0.4"
#uuid = { version = "1.1.2", features = ["serde", "v4"] }
