# fly.toml app configuration file generated for poac-api on 2023-05-07T22:05:48-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "poac-api"
primary_region = "sea"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
