name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install libraries required by drogon
        run: sudo apt-get install -y libjsoncpp-dev uuid-dev libssl-dev zlib1g-dev

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Run CMake
        run: cmake -B build -G Ninja

      - name: Build poac-api
        run: ninja
        working-directory: build
