name: C++

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - "src"
          - "test"
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.6.2
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path }}

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --recursive .
