name: C++

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - "src"
          - "include"
          - "tests"
          - "controllers"
          - "filters"
    steps:
      - uses: actions/checkout@v3

      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.8.0
        with:
          clang-format-version: '14'
          check-path: ${{ matrix.path }}

  cpplint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: cpplint --recursive .

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install libraries required by drogon
        run: sudo apt-get install -y libjsoncpp-dev uuid-dev libssl-dev zlib1g-dev

      - name: Install Ninja
        run: sudo apt-get install -y ninja-build

      - name: Run CMake
        run: cmake -B build -G Ninja

      - name: Build poac-api
        run: ninja
        working-directory: build
