name: Rust

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
      - name: Build
        run: cargo build --verbose

  #  format:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v3.2.0
  #      - run: cargo fmt --all -- --check
  #
  #  lint:
  #    runs-on: ubuntu-latest
  #
  #    steps:
  #      - uses: actions/checkout@v3.2.0
  #      - uses: actions-rs/clippy-check@v1
  #        with:
  #          token: ${{ secrets.GITHUB_TOKEN }}
  #          args: --all-targets --all-features -- -D clippy::all -D warnings

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.2.0
      - name: Run tests
        run: cargo test --all --verbose
