name: Shuttle

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # 10 times per day
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
